feat: added getCrossMarginInfo and getCrossMarginHistory methods, upd…
ElectraFinance/sdk pull request #20
Opened 2023-06-12 12:59 UTC by cheshirrrcat

…ated cfdHistorySchema and added crossMarginHistorySchema

2023-06-12 13:28 UTC, meafmira commented on src/services/BlockchainService/schemas/cfdHistorySchema.ts
> +});
А как это работает? Это же неправильное использование `transform`. `transform` ведь трансформирует именно сами данные, а не тип. Тут не должно буть упоминаний `z.string()` или `z.number()`. `transform` дает тебе `response`, с которым тебе нужно что-то сделать. А тут ты вроде пытаешь поменять саму схему, для этого же нужен `extend` https://zod.dev/?id=transform

2023-06-12 13:32 UTC, meafmira requested changes

2023-06-12 13:32 UTC, meafmira commented on src/services/BlockchainService/schemas/cfdHistorySchema.ts
> +});
```suggestion
export const cfdHistorySchema = baseHistorySchema.extend({
  instrumentAddress: z.string(),
});

export const crossMarginHistorySchema = baseHistorySchema.extend({
  instrumentIndex: z.number(),
});
```

2023-06-12 14:19 UTC, meafmira commented on src/services/BlockchainService/schemas/cfdHistorySchema.ts
> +});
Но это в любом случае не будет работать. Ты пробовал это использовать? У тебя всегда в ответе в `instrumentAddress` будет приходить `z.string()`. Там не будет никакого адреса в таком случае. Там нет `extend`, потому что это больше не схема. Тут надо решать по-другому. Сначала экстендить эту схему, а потом к базовой применять `transform`

2023-06-12 14:27 UTC, cheshirrrcat commented on src/services/BlockchainService/schemas/cfdHistorySchema.ts
> +});
@meafmira пробовал и это не работает)
Сейчас сделаю по-другому

2023-06-12 15:36 UTC, cheshirrrcat commented on src/services/BlockchainService/schemas/cfdHistorySchema.ts
> +});
Поправил

2023-06-13 08:23 UTC, meafmira approved these changes

2023-06-13 08:25 UTC, lobotomoe approved these changes

2023-06-13 08:25 UTC, lobotomoe commented on src/services/BlockchainService/index.ts
> +    this.getCrossMarginInfo = this.getCrossMarginInfo.bind(this);
Рядом бы поместить.

2023-06-13 08:55 UTC, cheshirrrcat commented on src/services/BlockchainService/index.ts
> +    this.getCrossMarginInfo = this.getCrossMarginInfo.bind(this);
Готово

2023-06-13 08:58 UTC, merged